-- Read-only staging catalog verification; run immediately after the matching migration.
select current_database(), current_setting('server_version');
select 'core.business_units' as expected_table, to_regclass('core.business_units') is not null as must_be_true;
select 'core.business_units' as expected_rls, relrowsecurity as must_be_true from pg_class where oid = 'core.business_units'::regclass;
select 'core.branches' as expected_table, to_regclass('core.branches') is not null as must_be_true;
select 'core.branches' as expected_rls, relrowsecurity as must_be_true from pg_class where oid = 'core.branches'::regclass;
select 'core.teams' as expected_table, to_regclass('core.teams') is not null as must_be_true;
select 'core.teams' as expected_rls, relrowsecurity as must_be_true from pg_class where oid = 'core.teams'::regclass;
select 'core.team_memberships' as expected_table, to_regclass('core.team_memberships') is not null as must_be_true;
select 'core.team_memberships' as expected_rls, relrowsecurity as must_be_true from pg_class where oid = 'core.team_memberships'::regclass;
select 'portfolio.projects' as expected_table, to_regclass('portfolio.projects') is not null as must_be_true;
select 'portfolio.projects' as expected_rls, relrowsecurity as must_be_true from pg_class where oid = 'portfolio.projects'::regclass;
select 'portfolio.goals' as expected_table, to_regclass('portfolio.goals') is not null as must_be_true;
select 'portfolio.goals' as expected_rls, relrowsecurity as must_be_true from pg_class where oid = 'portfolio.goals'::regclass;
select 'portfolio.tasks' as expected_table, to_regclass('portfolio.tasks') is not null as must_be_true;
select 'portfolio.tasks' as expected_rls, relrowsecurity as must_be_true from pg_class where oid = 'portfolio.tasks'::regclass;
select 'governance.decisions' as expected_table, to_regclass('governance.decisions') is not null as must_be_true;
select 'governance.decisions' as expected_rls, relrowsecurity as must_be_true from pg_class where oid = 'governance.decisions'::regclass;
select 'governance.policies' as expected_table, to_regclass('governance.policies') is not null as must_be_true;
select 'governance.policies' as expected_rls, relrowsecurity as must_be_true from pg_class where oid = 'governance.policies'::regclass;
select 'governance.approval_requests' as expected_table, to_regclass('governance.approval_requests') is not null as must_be_true;
select 'governance.approval_requests' as expected_rls, relrowsecurity as must_be_true from pg_class where oid = 'governance.approval_requests'::regclass;
select 'governance.approval_decisions' as expected_table, to_regclass('governance.approval_decisions') is not null as must_be_true;
select 'governance.approval_decisions' as expected_rls, relrowsecurity as must_be_true from pg_class where oid = 'governance.approval_decisions'::regclass;
select 'finops.cost_centers' as expected_table, to_regclass('finops.cost_centers') is not null as must_be_true;
select 'finops.cost_centers' as expected_rls, relrowsecurity as must_be_true from pg_class where oid = 'finops.cost_centers'::regclass;
select 'finops.budgets' as expected_table, to_regclass('finops.budgets') is not null as must_be_true;
select 'finops.budgets' as expected_rls, relrowsecurity as must_be_true from pg_class where oid = 'finops.budgets'::regclass;
select 'finops.usage_records' as expected_table, to_regclass('finops.usage_records') is not null as must_be_true;
select 'finops.usage_records' as expected_rls, relrowsecurity as must_be_true from pg_class where oid = 'finops.usage_records'::regclass;
select 'core.core_team_membership_agent_unique' as expected_index, to_regclass('core.core_team_membership_agent_unique') is not null as must_be_true;
select 'core.core_team_membership_human_unique' as expected_index, to_regclass('core.core_team_membership_human_unique') is not null as must_be_true;
select 'governance.governance_policy_global_unique' as expected_index, to_regclass('governance.governance_policy_global_unique') is not null as must_be_true;
select 'governance.governance_policy_org_unique' as expected_index, to_regclass('governance.governance_policy_org_unique') is not null as must_be_true;
select 'core.core_business_units_org_idx' as expected_index, to_regclass('core.core_business_units_org_idx') is not null as must_be_true;
select 'core.core_branches_unit_idx' as expected_index, to_regclass('core.core_branches_unit_idx') is not null as must_be_true;
select 'core.core_teams_branch_idx' as expected_index, to_regclass('core.core_teams_branch_idx') is not null as must_be_true;
select 'portfolio.portfolio_projects_org_status_idx' as expected_index, to_regclass('portfolio.portfolio_projects_org_status_idx') is not null as must_be_true;
select 'portfolio.portfolio_goals_project_status_idx' as expected_index, to_regclass('portfolio.portfolio_goals_project_status_idx') is not null as must_be_true;
select 'portfolio.portfolio_tasks_project_status_idx' as expected_index, to_regclass('portfolio.portfolio_tasks_project_status_idx') is not null as must_be_true;
select 'governance.governance_decisions_project_time_idx' as expected_index, to_regclass('governance.governance_decisions_project_time_idx') is not null as must_be_true;
select 'governance.governance_approval_queue_idx' as expected_index, to_regclass('governance.governance_approval_queue_idx') is not null as must_be_true;
select 'finops.finops_budgets_org_period_idx' as expected_index, to_regclass('finops.finops_budgets_org_period_idx') is not null as must_be_true;
select 'finops.finops_usage_org_time_idx' as expected_index, to_regclass('finops.finops_usage_org_time_idx') is not null as must_be_true;
select 'finops.finops_usage_run_idx' as expected_index, to_regclass('finops.finops_usage_run_idx') is not null as must_be_true;
select conrelid::regclass, conname, contype, pg_get_constraintdef(oid) from pg_constraint where conrelid in ('core.business_units'::regclass, 'core.branches'::regclass, 'core.teams'::regclass, 'core.team_memberships'::regclass, 'portfolio.projects'::regclass, 'portfolio.goals'::regclass, 'portfolio.tasks'::regclass, 'governance.decisions'::regclass, 'governance.policies'::regclass, 'governance.approval_requests'::regclass, 'governance.approval_decisions'::regclass, 'finops.cost_centers'::regclass, 'finops.budgets'::regclass, 'finops.usage_records'::regclass) order by conrelid, conname;
select tgrelid::regclass, tgname, pg_get_triggerdef(oid), tgfoid = 'core.set_updated_at()'::regprocedure as expected_function from pg_trigger where not tgisinternal and tgrelid in ('core.business_units'::regclass, 'core.branches'::regclass, 'core.teams'::regclass, 'core.team_memberships'::regclass, 'portfolio.projects'::regclass, 'portfolio.goals'::regclass, 'portfolio.tasks'::regclass, 'governance.decisions'::regclass, 'governance.policies'::regclass, 'governance.approval_requests'::regclass, 'governance.approval_decisions'::regclass, 'finops.cost_centers'::regclass, 'finops.budgets'::regclass, 'finops.usage_records'::regclass) order by tgrelid, tgname;
select to_regprocedure('core.set_updated_at()') is not null as must_be_true;
